version: '3.8'

services:
  db:
    image: postgres:18
    container_name: financial-db
    environment:
      POSTGRES_USER: Jarod
      POSTGRES_PASSWORD: Konijnenberg
      POSTGRES_DB: financialapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: financial-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/financialapp
      SPRING_DATASOURCE_USERNAME: Jarod
      SPRING_DATASOURCE_PASSWORD: Konijnenberg
    ports:
      - "8080:8080"

volumes:
  pgdata:
